version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"

  - package-ecosystem: "gradle"
    directories:
      - "/template/android/"
    schedule:
      interval: "daily"
    labels:
      - "nitro-core"
      - "dependencies"
      - "kotlin"

  - package-ecosystem: "npm"
    directories:
      - "/template"
      - "/template/modules/*"
      - "/"
    schedule:
      interval: "daily"
    groups:
      rncli:
        patterns:
          - "@react-native-community/cli*"
      babel:
        patterns:
          - "@babel/*"
      react-native:
        patterns:
          - "@react-native/*"
          - "react-native"
